version: '2.1'

services:

  aggregation-consumer:
    image: ${DOCKER_IMAGE}
    command: >
      ./start-app.sh -s API
    ports:
    - "9000:9000"
    networks:
      skynet:
        aliases:
        - "aggregation-consumer"
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=logback-dev.xml
      HOST_ADDRESS: ${HOST_ADDRESS}
      JAR_NAME: ${JAR_NAME}
      PORT: 9000

  producer:
    image: mangatmodi/producer:latest
    command: >
      java -jar producer.jar --tcp
    networks:
      skynet:
        aliases:
        - "producer"
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=logback-dev.xml
      HOST_ADDRESS: ${HOST_ADDRESS}
      JAR_NAME: producer.jar

networks:
  skynet:
